# Generated by Django 5.2.1 on 2025-06-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_code',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='description',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('barber', 'name'), name='unique_service_name_per_barber'),
        ),
    ]
