# Generated by Django 5.2.1 on 2025-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_admin_admin_code_remove_barber_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
