# Generated by Django 5.2.1 on 2025-06-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_barber_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('barber', 'date'), name='unique_availability_date_per_barber'),
        ),
    ]
