# Generated by Django 5.2.1 on 2025-06-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('barber', 'date', 'slot'), name='unique_appointment_per_barber_date_slot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('client', 'date'), name='unique_appointment_per_client_date'),
        ),
    ]
