# Generated by Django 5.2.1 on 2025-06-05 19:42

import api.models.appointment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_per_barber_date_slot',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_per_client_date',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', api.models.appointment.AppointmentStatus['CANCELLED']), _negated=True), fields=('client', 'date'), name='unique_appointment_per_client_date_if_not_cancelled'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', api.models.appointment.AppointmentStatus['CANCELLED']), _negated=True), fields=('barber', 'date', 'slot'), name='unique_appointment_per_barber_date_slot_if_not_cancelled'),
        ),
    ]
