# Generated by Django 5.2.1 on 2025-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_appointment_unique_appointment_per_client_date_if_not_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('client', 'barber'), name='unique_client_review_per_barber'),
        ),
    ]
