# Generated by Django 5.2.1 on 2025-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
