# Generated by Django 5.2.1 on 2025-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_barber_name_barber_surname_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barber',
            name='surname',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
