# Generated by Django 5.2.1 on 2025-06-15 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_barber_name_alter_barber_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed (E.164 format).", regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
