# Generated by Django 5.2.1 on 2025-07-03 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Username may only contain ASCII letters, digits, and underscores (_).', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
