# Generated by Django 5.2.1 on 2025-07-18 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may only contain ASCII letters, digits, and underscores (_).', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='api.appointment')),
                ('original_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
            ],
        ),
    ]
