# Generated by Django 5.2.1 on 2025-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_appointment_services_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', through='api.AppointmentService', to='api.service'),
        ),
    ]
