# Generated by Django 5.2.1 on 2026-07-04 08:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_client_phone_verified_at_alter_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(upload_to='images/portfolio/')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('featured', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BarberManager', max_length=100)),
                ('tagline', models.CharField(default='Precision cuts. Effortless booking.', max_length=180)),
                ('description', models.TextField(blank=True, default='A modern barbershop built around craft, comfort, and dependable service.')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('maps_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('currency_code', models.CharField(default='GHS', max_length=3)),
                ('currency_symbol', models.CharField(default='GH₵', max_length=8)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=64)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Map of weekday labels to display hours.')),
                ('home_visits_enabled', models.BooleanField(default=True)),
                ('home_visit_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_radius_km', models.PositiveSmallIntegerField(default=15)),
                ('booking_horizon_days', models.PositiveSmallIntegerField(default=60)),
                ('cancellation_notice_hours', models.PositiveSmallIntegerField(default=2)),
                ('reminder_minutes', models.PositiveSmallIntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'shop settings',
            },
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_per_client_date_if_not_cancelled',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_per_barber_date_slot_if_not_cancelled',
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='home_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location_type',
            field=models.CharField(choices=[('SHOP', 'SHOP'), ('HOME', 'HOME')], default='SHOP', max_length=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notification_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='travel_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('NO_SHOW', 'NO_SHOW')], default='ONGOING', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'NO_SHOW']), _negated=True), fields=('client', 'date'), name='unique_active_appointment_per_client_date'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'NO_SHOW']), _negated=True), fields=('barber', 'date', 'slot'), name='unique_active_appointment_per_barber_slot'),
        ),
    ]
