# Generated by Django 5.2.1 on 2026-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_portfolioitem_shopsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='announcement_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='announcement_text',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
