# Generated by Django 5.2.1 on 2026-07-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('before_image', models.ImageField(upload_to='images/before-after/before/')),
                ('after_image', models.ImageField(upload_to='images/before-after/after/')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_after_work', to='api.barber')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_after_work', to='api.service')),
            ],
            options={
                'ordering': ('display_order', '-created_at'),
            },
        ),
    ]
