# Generated by Django 5.2.1 on 2026-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('DEPOSIT', 'DEPOSIT'), ('FULL', 'FULL')], default='NONE', max_length=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PENDING', 'PENDING'), ('PAID', 'PAID')], default='UNPAID', max_length=8),
        ),
    ]
