# Generated by Django 5.2.1 on 2026-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_appointment_paid_at_appointment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('CORE', 'CORE'), ('TREATMENT', 'TREATMENT'), ('LOCS', 'LOCS'), ('PREMIUM', 'PREMIUM')], default='CORE', help_text='Categorizes the service for the public menu.', max_length=16),
        ),
    ]
