FROM python:3.12-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings.prod

COPY requirements/prod.txt requirements/base.txt requirements/
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY . .

COPY ./entrypoint.sh .
RUN chmod +x ./entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]

CMD ["sh", "-c", "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8080} --workers=1 --threads=4 --worker-class=sync --timeout=60 --max-requests=500 --max-requests-jitter=50"]
