FROM python:3.12-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings.dev

RUN apk add --no-cache build-base graphviz graphviz-dev

COPY requirements/dev.txt requirements/base.txt requirements/
RUN pip install -r requirements/dev.txt

COPY . .

COPY ./entrypoint.sh .
RUN chmod +x ./entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]